function gid2gmt(gidmesh,outfile)
%=====================================================
%function gid2gmt(gidmesh,outfile)
%
% Convert from GiD mesh format into gmt format
% 
% Input:
%   gidmesh: gid mesh file generated by GiD
%   outfile: output file
%
% Output:
%   None
% 
% Hua Wang @ Uni Leeds, 10/11/2009
%=====================================================

%trimesh=struct('tri',{},'x',{},'y',{});
%tri: m-by-3 matrix for triangular connectivity
%x/y: n-by-1 matrix for x and y coordinates

[trim]=gid2mat(gidmesh);

ntri=size(trim.tri,1);
nvtx=length(trim.x);

fid=fopen(outfile,'w');
for i=1:ntri
  vtx1=trim.tri(i,1);
  vtx2=trim.tri(i,2);
  vtx3=trim.tri(i,3);
  fprintf(fid,'>\n');
  fprintf(fid,'%-10.4f %-10.4f \n',trim.x(vtx1),trim.y(vtx1));
  fprintf(fid,'%-10.4f %-10.4f \n',trim.x(vtx2),trim.y(vtx2));
  fprintf(fid,'%-10.4f %-10.4f \n',trim.x(vtx3),trim.y(vtx3));
end
fprintf(fid,'>\n');
fclose(fid);
